Disable -Werror=non-virtual-dtor for stooling
When building on Arch Linux, this warning causes a fatal build error:

    Scanning dependencies of target stooling
    [ 16%] Building CXX object libraries/stooling/src/CMakeFiles/stooling.dir/CustomToolInvocation.cpp.o
    In file included from <skel-cl>/libraries/stooling/libraries/llvm/include/clang/Frontend/CommandLineSourceLoc.h:19:0,
                     from <skel-cl>/libraries/stooling/libraries/llvm/include/clang/Frontend/FrontendOptions.h:13,
                     from <skel-cl>/libraries/stooling/libraries/llvm/include/clang/Frontend/CompilerInvocation.h:19,
                     from <skel-cl>/libraries/stooling/libraries/llvm/include/clang/Frontend/CompilerInstance.h:15,
                     from <skel-cl>/libraries/stooling/src/CustomToolInvocation.cpp:21:
    <skel-cl>/libraries/stooling/libraries/llvm/include/llvm/Support/CommandLine.h: In instantiation of ‘class llvm::cl::opt<unsigned int>’:
    <skel-cl>/libraries/stooling/libraries/llvm/include/llvm/Support/CommandLine.h:1267:1:   required from here
    <skel-cl>/libraries/stooling/libraries/llvm/include/llvm/Support/CommandLine.h:1148:7: error: base class ‘class llvm::cl::opt_storage<unsigned int, false, false>’ has accessible non-virtual destructor [-Werror=non-virtual-dtor]
     class opt : public Option,
       ^
    compilation terminated due to -Wfatal-errors.
    cc1plus: all warnings being treated as errors
    libraries/stooling/src/CMakeFiles/stooling.dir/build.make:54: recipe for target 'libraries/stooling/src/CMakeFiles/stooling.dir/CustomToolInvocation.cpp.o' failed
    make[2]: *** [libraries/stooling/src/CMakeFiles/stooling.dir/CustomToolInvocation.cpp.o] Error 1
    CMakeFiles/Makefile2:266: recipe for target 'libraries/stooling/src/CMakeFiles/stooling.dir/all' failed
    make[1]: *** [libraries/stooling/src/CMakeFiles/stooling.dir/all] Error 2
    Makefile:86: recipe for target 'all' failed
    make: *** [all] Error 2